/***************************************************************
 * copyright (c) 2009, gaocheng
 * all rights reserved.
 *
 * file name   : mouse.c
 * version     : 1.0
 * description :
 * author      : gaocheng
 * date        : 2011-04-22
 ***************************************************************/

/***************************************************************
 include header file
 ***************************************************************/
#include <core.h>

/***************************************************************
 global variable declare
 ***************************************************************/
/* fill */
#define MOUSE_FILL VGA_COLOR_WHITE
/* profile */
#define MOUSE_PROF VGA_COLOR_BLACK
/* transparent */
#define MOUSE_TRAN VGA_TRAN

#define MOUSE_ICON_X 16
#define MOUSE_ICON_Y 32

LOCALD const enum vga_color mouse_icon_data[MOUSE_ICON_Y][MOUSE_ICON_X] = {
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF }, // 0x1,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_PROF }, // 0x3,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_PROF }, // 0x5,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x9,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x11,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x21,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x41,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x81,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x101,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x201,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x401,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x801,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x1001,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x2001,
    { MOUSE_TRAN, MOUSE_PROF, MOUSE_PROF, MOUSE_PROF, MOUSE_PROF, MOUSE_PROF, MOUSE_PROF, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x7f01,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x111,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF }, // 0x229,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_PROF }, // 0x225,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_PROF }, // 0x443,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF }, // 0x441,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x880,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x880,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x1100,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_FILL, MOUSE_FILL, MOUSE_FILL, MOUSE_PROF, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x1100,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_PROF, MOUSE_PROF, MOUSE_PROF, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0xe00,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x0,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x0,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x0,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x0,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x0,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN }, // 0x0,
    { MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN, MOUSE_TRAN } // 0x0
};

/* 鼠标图标 16x32 */
LOCALD const struct os_icon mouse_icon[32] = {
    ICON_RGB24_16_32, {
        mouse_icon_data
    }
};

/* 鼠标屏幕缓存 */
LOCALD enum vga_color mouse_icon_shadow[32][16] = { MOUSE_TRAN };

/***************************************************************
 function declare
 ***************************************************************/
/***************************************************************
 * description :
 * history     :
 ***************************************************************/
os_void paint_mouse(screen_csys *focus)
{
    struct os_icon icon;
    GLOBALDIF screen_csys sps = {0, 0};
    GLOBALDIF screen_csys spe = {0, 0};
    GLOBALDIF icon_csys ips = {0, 0};
    GLOBALDIF icon_csys ipe = {0, 0};
    lock_t eflag;

    if (OS_NULL != focus) {
        //mem_set(mouse_icon_buffer, MOUSE_TRAN, sizeof(mouse_icon_data));

        /* 恢复上次鼠标所在区域的影像 */
        icon.choice = ICON_RGB24_16_32;
        icon.u.data_16_32_24 = (os_void *) mouse_icon_shadow;
        paint_icon(&sps, &icon, &ips, &ipe); /* 16x32 */

        lock_int(eflag);

        /* 计算本次鼠标终点 */
        sps.x = focus->x - MOUSE_ICON_X;
        sps.y = focus->y;
        spe.x = focus->x;
        spe.y = focus->y + MOUSE_ICON_Y;
        /* bug ip初始化, 否则在屏幕边缘突然移动到中央区域鼠标残缺 */
        ips.x = 0;
        ips.y = 0;
        ipe.x = MOUSE_ICON_X;
        ipe.y = MOUSE_ICON_Y;
        if (MOUSE_ICON_X > focus->x) {
            sps.x = 0;
            ips.x = MOUSE_ICON_X - focus->x;
        }
        if ((current_resolution().y - MOUSE_ICON_Y) < focus->y) {
            spe.y = current_resolution().y;
            ipe.y = current_resolution().y - focus->y;
        }

        /* 保存本次鼠标放置位置的影像 */
        read_screen(&sps, mouse_icon_shadow, &ips, &ipe);

        unlock_int(eflag);

        /* 在本次焦点位置画鼠标 */
        paint_icon(&sps, mouse_icon, &ips, &ipe); /* 16x32 */
    }
}

