;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; (C)Copyright 2009, gaocheng.
;
; All Rights Reserved.
;
; file name  : dlayout.inc
; version    : 1.0
; author     : gaocheng
; date       : 2011-04-22
; description: disk layout
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

DISK_DRIVER_TYPE = 00H

BYTE_PER_SECTOR = 200H

ASM16_LBA = 12H
COS16_LBA = 24H
