;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; /* (C)Copyright 2009, gaocheng.
;
;    All Rights Reserved.
;
;    file name  : media.inc
;    version    : 1.0
;    author     : gaocheng
;    date       : 2011-04-22
;    description: media information */
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; /* macro */

DISK_DRIVER_TYPE = 0; /* 00H */
